version: '3.9'

services:
  customer-service:
    image: customer-service
    build: customer-service
    container_name: customer-service
    ports:
      - "8080:8080"
    networks:
      - consumer-producer
    depends_on:
      - address-service

  address-service:
    image: address-service
    build: address-service
    container_name: address-service
    networks:
      - consumer-producer

networks:
  consumer-producer:







# networks:
#   network-eureka:

# services:

#   registry:
#     image: registry:latest
#     container_name: registry
#     ports:
#       - "8761:8761"
#     expose:
#       - "8760-8770"
#     networks:
#       - network-eureka

#   gateway:
#     image: gateway:latest
#     container_name: gateway
#     ports:
#       - "80:8080"
#     depends_on:
#       - registry
#     environment:
#       - JAVA_OPTS=
#         -DEUREKA_SERVER=http://registry:8761/eureka
#     networks:
#       - network-eureka

#   customer:
#     image: customer:latest
#     container_name: customer
#     ports:
#       - "8081:8080"
#     depends_on:
#       - "registry"
#       - "gateway"
#     environment:
#       - JAVA_OPTS=
#         -DEUREKA_SERVER=http://registry:8761/eureka
#     networks:
#       - network-eureka

#   address:
#     image: address:latest
#     container_name: address
#     ports:
#       - "8082:8080"
#     depends_on:
#       - "registry"
#       - "gateway"
#     environment:
#       - JAVA_OPTS=
#         -DEUREKA_SERVER=http://registry:8761/eureka
#     networks:
#       - network-eureka
