version: '3.9'

services:
  gateway-service:
    image: gateway-service
    build: gateway-service
    container_name: gateway-service
# TODO problem with BuildPacks
#    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "80:80"
    networks:
      - network-eureka
    depends_on:
      - customer-service
      - address-service
      - eureka-server

  customer-service:
    image: customer-service
    build: customer-service
    container_name: customer-service
# TODO problem with BuildPacks
#    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - network-eureka
    depends_on:
      - eureka-server

  address-service:
    image: address-service
    build: address-service
    container_name: address-service
# TODO problem with BuildPacks
#    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - network-eureka
    depends_on:
      - eureka-server

  eureka-server:
    build: eureka-service
    container_name: eureka-server
# TODO problem with BuildPacks
#    mem_limit: 350m
    ports:
      - "8761:8761"
    expose:
      - "8760-8770"
    networks:
      - network-eureka

networks:
  network-eureka:
