version: '3.9'

services:

  eureka-service:
    build: eureka-service
    container_name: eureka-service
    # TODO problem with BuildPacks
    #    mem_limit: 350m
    ports:
      - "8761:8761"
    networks:
      - network-eureka


  gateway-service:
    image: gateway-service
    build: gateway-service
    container_name: gateway-service
#    # TODO problem with BuildPacks
#    #    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "80:80"
    networks:
      - network-eureka
    depends_on:
      - eureka-service
      - customer-service
      - address-service

  customer-service:
    image: customer-service
    build: customer-service
    container_name: customer-service
    #    # TODO problem with BuildPacks
    #    #    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - network-eureka
    depends_on:
      - eureka-service

  address-service:
    image: address-service
    build: address-service
    container_name: address-service
    #    # TODO problem with BuildPacks
    #    #    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - network-eureka
    depends_on:
      - eureka-service

networks:
  network-eureka:
