### Over GATEWAY
### Custmer
POST http://docker/myapp/services/customer/customers
Forwarded: for="docker;host=docker"
Content-Type: application/json

{
  "firstName": "Foo",
  "lastName": "Bar"
}
###
POST http://docker/myapp/services/customer/customers
Forwarded: for="docker;host=docker"
Content-Type: application/json

{
  "firstName": "Fazz",
  "lastName": "Bazz",
  "gender" : "m"
}

### Address
POST http://docker/myapp/services/address/addresses
Forwarded: for="docker;host=docker"
Content-Type: application/json

{
  "streetName": "Fifth Avenue",
  "streetNr": "103"
}


### Address over Customer
GET http://docker/myapp/services/customer/addresses
Forwarded: for="docker;host=docker"






### Directly
GET http://localhost:8080/myapp/services/customer/addresses
Forwarded: for="docker;host=docker"


### Custmer
POST http://localhost:9000/customers
Content-Type: application/json

{
  "firstName": "Foo",
  "lastName": "Bar"
}


### Address
POST http://localhost:9001/addresses
Content-Type: application/json

{
  "streetName": "Fifth Avenue",
  "streetNr": "103"
}
