spring:
  profiles:
    active: default
    include:
      - common
      - h2
  application:
    name:  customer-service

logging:
  level:
    #    root: warn
    ch.keepcalm.demo: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd E HH:mm:ss.SSS}){blue} - %clr(${spring.application.name:-}){green} - %clr(%-40.40logger{0}){magenta} - %clr(%m){green}%n"

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
---
server.port: 80

eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

spring:
  config:
    activate:
      on-profile: docker
