## Eureka
eureka:
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true
    region: default
    registry-fetch-interval-seconds: 2
    instance-info-replication-interval-seconds: 2
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: false
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}


# Used for Traverson Ribbon Client
ribbon:
  restclient:
    enabled: true
