spring:
  profiles:
    active: default
    include:
      - common
      - h2
  application:
    name:  customer

logging:
  level:
    #    root: warn
    ch.keepcalm.demo: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd E HH:mm:ss.SSS}){blue} - %clr(${spring.application.name:-}){green} - %clr(%-40.40logger{0}){magenta} - %clr(%m){green}%n"

server:
  port: 8080
