spring:
  application:
    name:  gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
          url-expression: "uri"
      # avoid sending forwarded/x-forwarded headers from api-gateway, as they overwrite forwarded headers from revers-proxy or loadbalancer
      forwarded:
        enabled: false
      x-forwarded:
        enabled: true
        prefix-enabled: true # this header modifies the uri of the request within the called service
        prefix-append: false
        proto-enabled: false
        proto-append: false
        port-enabled: false
        port-append: false
        host-enabled: false
        host-append: false
        for-enabled: false
        for-append: false

      routes:
        - id: customer-service
          predicates:
            - Path=/myapp/services/customer/**
          filters:
            - StripPrefix=3
          uri: http://localhost:9000

logging:
  level:
    root: debug

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true
  info:
    git:
      mode: full

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
---
server.port: 80

eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

spring:
  config:
    activate:
      on-profile: docker

  cloud:
    gateway:
      routes:
        - id: customer-service
          predicates:
            - Path=/myapp/services/customer/**
          filters:
            - StripPrefix=3
          uri: lb://customer-service
