spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
          url-expression: "uri"

      forwarded.enabled: true
      x-forwarded.enabled: true
      x-forwarded.forEnabled: true
      x-forwarded.protoEnabled: true

      routes:


        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1

        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/address/**
          filters:
            - StripPrefix=1

        - id: add_request_header_route
          uri: https://httpbin.org
          predicates:
            - Path=/get/**
          filters:
            - AddRequestHeader=My-Header-Good,Good
            - AddRequestHeader=My-Header-Remove,Remove
            - AddRequestParameter=var, good
            - AddRequestParameter=var2, remove
            - MapRequestHeader=My-Header-Good, My-Header-Bad
            - MapRequestHeader=My-Header-Set, My-Header-Bad
            - SetRequestHeader=My-Header-Set, Set
            - RemoveRequestHeader=My-Header-Remove
            - RemoveRequestParameter=var2


