management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true
  info:
    git:
      mode: full

#server:
#  forward-headers-strategy: framework

# Used for Traverson Ribbon Client
ribbon:
  restclient:
    enabled: true
