eureka:
  instance:
    hostname: gateway
    lease-renewal-interval-in-seconds: 2

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

