spring:
  profiles:
    active: default
    include:
      - common
      - routes
      - registry

  application:
    name:  gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
          url-expression: "uri"
      forwarded:
        enabled: true

server:
  port: 8080
