spring:
  profiles:
    active: default
    include: common
  application:
    name: registry

server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
  instance:
    lease-renewal-interval-in-seconds: 2
