spring:
  profiles:
    active: default
    include: common
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    lease-renewal-interval-in-seconds: 2
