spring:
  profiles:
    active: default
    include:
      - common
      - h2
  application:
    name:  address-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true
  info:
    git:
      mode: full

server:
  forward-headers-strategy: framework
  port: 9001


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
---
server.port: 80

eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

spring:
  config:
    activate:
      on-profile: docker

---
spring:
  config:
    activate:
      on-profile: standalone
eureka:
  client:
    enabled: false
