spring:
  profiles:
    active: default
    include:
      - common
      - h2
  application:
    name:  address-service

server:
  port: 9001


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
---
server.port: 80

eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

spring:
  config:
    activate:
      on-profile: docker
